# Servidor Web (Apache + PHP)
  web:
    image: php:8.2-apache
    container_name: tp_apache_web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html/  # <-- OJO: Nota que la ruta interna cambió a /var/www/html/
    networks:
      - tp-network
    depends_on:
      - db